import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import DashboardWrapper from '@/components/dashboard'
import { Text } from '@chakra-ui/react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <DashboardWrapper
        pageTitle="TransMonitor"
        background="white"
        padding="30px"
      >
        <Text>gfhjkklgfhhjklkl</Text>
        </DashboardWrapper>
      </main>
    </>
  )
}
