import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import DashboardWrapper from '@/components/dashboard'
import { SimpleGrid, Text } from '@chakra-ui/react'
import Transaction from '@/components/Transaction'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <DashboardWrapper
        pageTitle="TransMonitor"
        background="white"
        padding="30px"
      >
        <SimpleGrid columns={[1, null, 4]} spacing='9px'>
          <Transaction title='Daily Transaction Volume' total={2342}/>
          <Transaction title='Daily Transaction Value' total={4000000} currency={true}/>
          <Transaction title='Total Transaction Volume' total={452000}/>
          <Transaction title='Total Transaction Value' total={4000000} currency={true}/>
        </SimpleGrid>
        </DashboardWrapper>
      </main>
    </>
  )
}
